from typing import List, Dict, Protocol, Any

class SystemRepository(Protocol):
    def get_failed_nodes(self) -> List[str]: ...
    def get_node_details(self, node_id: str) -> Dict[str, Any]: ...
    def assign_crew(self, node_id: str, crew_id: str) -> bool: ...

class AgentRepository(Protocol):
    def get_available_crews(self) -> List[str]: ...
    def get_weather_at_location(self, location: str) -> int: ...
    def estimate_repair_time(self, node_id: str, crew_id: str) -> int: ...
    def estimate_arrival_time(self, node_id: str, crew_id: str) -> int: ...
    def get_crew_location(self, crew_id: str) -> str: ...
    def get_crew_remaining_capacity(self, crew_id: str) -> int: ...
    def estimate_travel_time_in_ms(self, origin: str, destination: str) -> int: ...
    def estimate_repair_time_in_ms(self, node: str) -> int: ...
