from typing import List, Dict, Protocol, Any
from datetime import datetime

class SystemRepository(Protocol):
    def get_failed_nodes(self) -> List[str]: ...
    def get_node_details(self, node_id: str) -> Dict[str, Any]: ...
    def assign_crew(self, node_id: str, crew_id: str) -> bool: ...

class AgentRepository(Protocol):
    def get_weather_at_location(self, location: str) -> int: ...
    def is_holiday(self, date: datetime) -> bool: ...
    def is_weekend(self, date: datetime) -> bool: ...
    def get_time_of_day(self, hour: int) -> str: ...
    def estimate_travel_time(self, origin: str, destination: str) -> int: ...
    def estimate_repair_time(self, node: str) -> int: ...
    def crew_location(self, crew_id: str) -> str: ...
    def is_crew_available(self, crew_id: str) -> bool: ...
    def get_available_crews(self) -> List[str]: ...
